name: Brew install + Check init script

on: [push, pull_request]

jobs:
  brew:
    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Remove pre-installed pod command
      run: rm '/usr/local/bin/pod'
    - name: Install formulas by homebrew + bundle
      run: |
        brew tap homebrew/bundle
        brew bundle
  ruby:
    runs-on: ubuntu-latest
    container: docker://alpine
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies by apk
        run: apk add ruby ruby-dev make gcc libc-dev
      - name: Execute ruby-init.sh
        run: ./scripts/ruby-init.sh
      - name: Check gems
        run: |
          which pry kramdown
          gem list | grep neovim
  python:
    runs-on: ubuntu-latest
    container: docker://alpine
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies by apk
        run: apk add python3 python3-dev gcc libc-dev
      - name: Execute python-init.sh
        run: ./scripts/python-init.sh
      - name: Check packages
        run: |
          which aws sam
          pip3 list | grep pynvim
  node:
    runs-on: ubuntu-latest
    container: docker://alpine
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies by apk
        run: apk add nodejs npm
      - name: Execute node-init.sh
        run: ./scripts/node-init.sh
      - name: Check packages
        run: |
          which tsc yarn
          npm list -g | grep neovim
  neovim:
    runs-on: ubuntu-latest
    container: docker://alpine
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies by apk
        run: apk add neovim curl git python3 python3-dev gcc libc-dev
      - name: Execute neovim-init.sh
        run: ./scripts/neovim-init.sh
      - name: Check packages
        run: |
          which nvim
          pip3 list | grep pynvim
          ls $HOME/.config/nvim/dein/repos/github.com/Shougo/dein.vim
          ls $HOME/.config/nvim/dein/repos/github.com | grep atton
          ls $HOME/.config/nvim/dein/repos/github.com | grep Shougo
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup pre-installed docker images
        run: docker images -aq | xargs docker rmi
      - name: Execute docker-init.sh
        run: ./scripts/docker-init.sh
      - name: Check images
        run: |
          docker images | grep alpine
          docker images | grep centos
          docker images | grep fedora
          docker images | grep ubuntu
