name: Brew bundle and Verify init scripts

on: [push, pull_request]

# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

jobs:
  homebrew-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remove cocoapods
      run: rm -f /usr/local/bin/pod
    - name: Install formulas by homebrew + bundle
      run: |
        brew update >& /dev/null
        brew tap homebrew/bundle
        brew bundle
  docker-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup pre-installed docker images
        run: docker images -aq | xargs docker rmi
      - name: Execute docker-init.sh
        run: bash scripts/docker-init.sh
      - name: Check images
        run: |
          docker images | egrep '^alpine\s+latest'
          docker images | egrep '^centos\s+latest'
          docker images | egrep '^atton/latex-make\s+latest'
          docker images | egrep '^atton/webpage-title\s+latest'
  vim-macos:
    runs-on: macos-latest
    steps:
      - name: Show version
        run: /usr/bin/vim --version
      - uses: actions/checkout@v2
      - name: Execute install.sh
        run: rm -rf $HOME/.config && bash install.sh
      - name: Validate .vimrc by system vim
        run: /usr/bin/vim -es -u NONE -c 'try | source $HOME/.vimrc | catch | cq! | endtry | q!'
