name: Search docker images

# Docker Hub Princing: https://hub.docker.com/pricing
# Free plan restricted 100 pull / 6 hour. So verification switched pull to only search.

on: [push, pull_request]

jobs:
  docker-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Search images
        run: |
          docker search latex-make    | grep atton
          docker search webpage-title | grep atton
