name: Verify docker-init script

on: [push, pull_request]

jobs:
  docker-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup pre-installed docker images
        run: docker images -aq | xargs docker rmi
      - name: Execute docker-init.sh
        run: ./scripts/docker-init.sh
      - name: Check images
        run: |
          docker images | egrep '^alpine\s+latest'
          docker images | egrep '^centos\s+latest'
          docker images | egrep '^atton/alpine-texlive-ja\s+latest'
          docker images | egrep '^atton/latex-make\s+latest'
          docker images | egrep '^atton/webpage-title\s+latest'
