name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      uses: actions/checkout@v2
    - name: Install formulas by homebrew + bundle
      run: |
        brew tap homebrew/bundle
        brew bundle
