name: Brew bundle

on: [push, pull_request]

# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

jobs:
  homebrew-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remove cocoapods
      run: rm -f /usr/local/bin/pod
    - name: Install formulas by homebrew + bundle
      run: |
        $(brew update >& /dev/null || true)
        brew tap homebrew/bundle
        brew bundle
